services:
  - type: web
    name: back-ecommerce
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app.main:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        value: tu_clave_secreta
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
