"""empty message

Revision ID: 51f05eae0c7d
Revises: d4e60180b37b
Create Date: 2025-04-18 19:20:08.897952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f05eae0c7d'
down_revision = 'd4e60180b37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.Text(), nullable=True))

    with op.batch_alter_table('cupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_Inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.drop_column('fecha')

    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    with op.batch_alter_table('cupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_Inicio')

    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
