"""areglo

Revision ID: 635892f1df76
Revises: 3ef14753bde7
Create Date: 2025-04-13 15:35:26.606660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635892f1df76'
down_revision = '3ef14753bde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
