"""empty message

Revision ID: a4e87496b9a7
Revises: ae8f6f6a0b11
Create Date: 2025-04-20 18:32:18.087210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e87496b9a7'
down_revision = 'ae8f6f6a0b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_constraint('carrito_venta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'venta', ['venta_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carrito_venta_id_fkey', 'venta', ['venta_id'], ['id'])

    # ### end Alembic commands ###
