"""empty message

Revision ID: ae8f6f6a0b11
Revises: b0a2c2967d87
Create Date: 2025-04-20 11:57:07.784365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8f6f6a0b11'
down_revision = 'b0a2c2967d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.alter_column('venta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('venta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
