"""empty message

Revision ID: d4e60180b37b
Revises: bbc879fade45
Create Date: 2025-04-17 23:10:12.463464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e60180b37b'
down_revision = 'bbc879fade45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cupon', ['cupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cupon_id')

    # ### end Alembic commands ###
