from .cliente_model import Cliente
from .cupon_model import Cupon
from .cliente_cupon_model import ClienteCupon
from .metodo_pago_model import MetodoPago
from .venta_model import Venta
from .resena_model import Resena
from .categoria_model import Categoria
from .marca_model import Marca
from .producto_model import Producto
from .imagen_producto_model import ImagenProducto
from .movimiento_model import Movimiento
from .usuario_model import Usuario
from .carrito_model import Carrito
from .bitacora_model import Bitacora
from .rol_model import Rol
from .permiso_model import Permiso
from .rol_permiso_model import RolPermiso